=pod

=head1 NAME

NX::Lock - OO Lock interface

=head1 VERSION

version 0.01

=head1 SYNOPSIS

 do {
   my $lock = NX::Lock->new("/tmp/foo.lock");
   die 'no lock!' unless defined $lock;
   # do something which requires the lock
 };
 # lock automatically released

=head1 DESCRIPTION

OO interface to flock.  The lock is automatically 
released when the lock object falls out of scope

=head1 CONSTRUCTOR

=head2 NX::Lock->new( $filename, %options )

On success returns a lock.

Blocks until the lock is obtained if in blocking mode.

Returns undef if in non blocking mode and lock 
could not be obtained.

Options:

=over 4

=item block

Blocking mode.

=item quit_on_fail

Quit the entire program (NOT die!) if not in
blocking mode and lock can not be obtained.

=item shared

Obtain a shared lock.

=back

=head1 METHODS

=head2 $lock-E<gt>release

Release the lock.

=head1 AUTHOR

Graham Ollis <plicease@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013 by Graham Ollis.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

